src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    // 1 : en attente
    // 2 : paiement validé
    // 3 : En cours de préparation
    // 4 : Expedié
    // 5 : Annulée

    #[ORM\Column]
    private ?int $state = null;

    #[ORM\Column(length: 255)]
    private ?string $carrierName = null;

    #[ORM\Column]
    private ?float $carrierPrice = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $delivery = null;

    /**
     * @var Collection<int, OrderDetail>
     */
    #[ORM\OneToMany(targetEntity: OrderDetail::class, mappedBy: 'myOrder', cascade: ['persist'])]
    private Collection $orderDetails;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $stripe_session_id = null;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getTotalWt() 
    {
        $totalTtc = 0;
        $products = $this->getOrderDetails();

        foreach ($products as $product) {
            $coeff = 1 + $product->getProductTva() / 100;
            $totalTtc += ($product->getProductPrice() * $coeff) * $product->getProductQuantity();
        }

        return $totalTtc + $this->getCarrierPrice();
    }

    public function getTotalTva() 
    {
        $totalTva = 0;
        $products = $this->getOrderDetails();
        
        foreach ($products as $product) {
            $coeff = $product->getProductTva() / 100;
            $totalTva += ($product->getProductPrice() * $coeff) * $product->getProductQuantity();
        }

        return $totalTva;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrierName;
    }

    public function setCarrierName(string $carrierName): static
    {
        $this->carrierName = $carrierName;

        return $this;
    }

    public function getCarrierPrice(): ?float
    {
        return $this->carrierPrice;
    }

    public function setCarrierPrice(float $carrierPrice): static
    {
        $this->carrierPrice = $carrierPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): static
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): static
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->add($orderDetail);
            $orderDetail->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): static
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getMyOrder() === $this) {
                $orderDetail->setMyOrder(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripe_session_id;
    }

    public function setStripeSessionId(?string $stripe_session_id): static
    {
        $this->stripe_session_id = $stripe_session_id;

        return $this;
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Dompdf\Dompdf;

class InvoiceController extends AbstractController
{
    // Impression PDF pour utilisateur connecté
    // vérification de la commande pour un utilisateur donné
    #[Route('/compte/facture/impression/{id_order}', name: 'app_invoice_customer')]
    public function invoiceCustomer(OrderRepository $orderRepository, $id_order): Response
    {
        $order = $orderRepository->findOneById($id_order);

        if(!$order) {
            return $this->redirectToRoute('app_account');
        }

        if($order->getUser() != $this->getUser()) {
            return $this->redirectToRoute('app_account');
        }

        $dompdf = new Dompdf();
        $html = $this->renderView('invoice/index.html.twig', [
            'order' => $order
        ]);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portait');
        $dompdf->render();
        $dompdf->stream('facture.pdf', [
            'Attachment' => false
        ]);
        exit();
       
    }

    // Impression PDF pour admin
    // vérification de la commande pour un utilisateur donné
    #[Route('/admin/facture/impression/{id_order}', name: 'app_invoice_admin')]
    public function invoiceAdmin(OrderRepository $orderRepository, $id_order): Response
    {
        $order = $orderRepository->findOneById($id_order);

        if(!$order) {
            return $this->redirectToRoute('admin');
        }

        $dompdf = new Dompdf();
        $html = $this->renderView('invoice/index.html.twig', [
            'order' => $order
        ]);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portait');
        $dompdf->render();
        $dompdf->stream('facture.pdf', [
            'Attachment' => false
        ]);
        exit();
       
    }
}

templates/invoice/index.html.twig
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <style>
        body {
           font-family: Roboto, sans-serif; 
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .text-left {
            text-align: left;
        }
        table {
            border-collapse: collapse;
        }
        table td, table th {
            border-top: 1px solid #ccc;
            padding: 0.5rem;
        }
    </style>
  </head>
  <body>
    <div class="text-center">

    <h3 class="text-left">Facture commande n° {{ order.id }}</h3>
        <table style="width: 100%; border-bottom: 1px solid gray;">
            <tr>
                <td style="width: 49%;">
                    <strong>La Boutique Française</strong> <br>
                    mon adresse <br>
                    code postal, ville, pays <br>
                    email@laboutiquefrancaise.fr<br>
                    0612345678<br>
                    
                </td>
                <td class="text-right">
                    {{ order.delivery|raw }}
                </td>
            </tr>
        </table>
    </div>
    <h5>Votre commande</h5>
    <table style="width: 100%;">
                <thead>
                    <tr>
                    <th scope="col" class="text-left">Produit</th>
                    <th scope="col" class="text-left">Quantité</th>
                    <th scope="col" class="text-left">Prix unitaire HT</th>
                    <th scope="col" class="text-left">TVA</th>
                    <th scope="col" class="text-right">Prix Total TTC</th>
                    </tr>
                </thead>
                <tbody>
                   
                    {% for product in order.orderDetails %}
                        <tr>
                            <td class="text-left" >{{ product.productName }}</td>
                            <td class="text-left">{{ product.productQuantity }}</td>
                            <td class="text-left">{{ product.productPrice | price}}</td>
                            <td class="text-left">{{ product.productTva}}%</td>
                            {% set coeff = 1 + (product.productTva / 100)  %}
                            <td class="text-right">{{ ((coeff * product.productPrice) * product.productQuantity) | price }}</td>
                            
                        </tr>
                    {% endfor %}
                        <tr>
                            <td class="text-left">Transporteur: {{ order.carrierName }}</td>
                            <td class="text-left">1</td>
                            <td></td>
                            <td></td>
                            <td class="text-right">{{ order.carrierPrice | price }}</td>
                        </tr>
                    
                </tbody>
            </table>

            <div class="text-right" style="margin-top: 10px;">
                <strong>Total H.T. :</strong> {{ (order.totalWt - order.totalTva)| price }} <br>
                Total TVA : {{ order.totalTva | price }} <br>
                <strong>Total T.T.C : {{ order.totalWt | price }} </strong><br>
            </div>


  </body>
</html>